doc/decisions/0001-record-architecture-decisions.md

Adding the document about using Architectural Decision Record for the project (using https://github.com/npryce/adr-tools)

Add ADR for the Framework

---

src/framework/db/sql.clj

Small fix in drop table clause.

missing call in 1-arity version of drop table

---

.github/workflows/test.yml
.gitignore
project.clj
src/framework/components/core.clj
src/framework/config/core.clj
src/framework/db/sql.clj
test/framework/core_test.clj

Adding gh actions

---

.github/clojars_deploy.bb
.github/workflows/deploy.yml
project.clj

Get version from `project.clj`, add `v` prefix and use it as a git tag.
```
git tag -s -a v0.0.1 -m "Test release"
git push origin v0.0.1
```

Add Clojars deployment

---

src/framework/components/app/core.clj

make->App accept a map as parameter

update framework version

---

src/framework/acl/core.clj
test/framework/acl/core_test.clj

ACL fine tuning based on usage

Users endpoint

---

.github/workflows/test.yml
.gitignore
project.clj
src/framework/rbac/core.clj
src/framework/route/core.clj
src/framework/session/core.clj
test/framework/interceptor/wrap_test.clj
test/framework/rbac/integration_test.clj
test/framework/rbac/interceptor_test.clj
test/framework/webserver/core_test.clj
test/framework_fixture.clj

Add support of RBAC and data ownership handling to xiana framework.
No breaking change for v0.3.0, it can be part of if, or different release.

Tiny rbac integration to development

---

README.org

Hi,
I amended a typo that I spotted :smile_cat: 
Cheers,
Marius

Amend typo: orders -> other

---

.github/clojars_deploy.bb

A brief summary of the changes including a description of the new behaviour or the fixed bug.
A brief description of any steps needed to demonstrate the new functionality or show the bug is fixed

slurp project-clj

---

.github/clojars_deploy.bb

A brief summary of the changes including a description of the new behaviour or the fixed bug.
A brief description of any steps needed to demonstrate the new functionality or show the bug is fixed

trim version

---

project.clj
src/framework/sse/core.clj

caused non processable SSE events on front end.

fix sse initialization

---

examples/acl/Docker/db.Dockerfile
examples/acl/config/test/config.edn
examples/acl/project.clj
examples/cli-chat/Docker/db.Dockerfile
examples/cli-chat/config/test/config.edn
examples/cli-chat/project.clj
examples/controllers/Docker/db.Dockerfile
examples/controllers/config/test/config.edn
examples/controllers/project.clj
examples/frames/Docker/db.Dockerfile
examples/frames/project.clj
examples/sessions/Docker/db.Dockerfile
examples/sessions/config/test/config.edn
examples/sessions/project.clj
project.clj
src/framework/db/core.clj

this PR allows passing jdbc-options map to `connect` & `in-transaction` functions. 
this functionality needed for this PR to frankie
https://github.com/Flexiana/Frankie/pull/488

ability to pass jdbc-opts to connect and in-transaction

---

examples/acl/project.clj
examples/cli-chat/project.clj
examples/controllers/project.clj
examples/frames/project.clj
examples/sessions/project.clj
examples/state-events/project.clj
project.clj
src/framework/handler/core.clj
src/framework/interceptor/queue.clj
test/framework/interceptor/queue_test.clj

Handler refactor

---

examples/sessions/test/integration.clj
src/xiana/commons.clj

Init dockerized postgres for integration tests 
`lein test` should pass without having a prepared db

Use docker for session-storage in fixture

---

examples/acl/config/dev/config.edn
examples/acl/config/test/config.edn
examples/acl/docker-compose.yml
examples/acl/project.clj
examples/cli-chat/config/dev/config.edn
examples/cli-chat/config/test/config.edn
examples/cli-chat/docker-compose.yml
examples/cli-chat/project.clj
examples/controllers/config/dev/config.edn
examples/controllers/config/test/config.edn
examples/controllers/docker-compose.yml
examples/controllers/project.clj
examples/frames/config/dev/config.edn
examples/frames/docker-compose.yml
examples/frames/project.clj
examples/sessions/project.clj
examples/state-events/project.clj
project.clj
src/framework/sse/core.clj

Use multiple sessions

---

examples/acl/project.clj
examples/cli-chat/project.clj
examples/cli-chat/src/backend/cli_chat/controller_behaviors/chat.clj
examples/controllers/project.clj
examples/frames/project.clj
examples/sessions/project.clj
examples/state-events/dev/user.clj
examples/state-events/project.clj
examples/state-events/src/backend/state_events/interceptors/event_process.clj
project.clj
src/framework/db/main.clj
src/framework/interceptor/core.clj
src/framework/scheduler/core.clj
src/framework/sse/core.clj
src/framework/webserver/core.clj
src/framework/websockets/core.clj
test/framework/web_socket/integration_test.clj

- added timbre to deps
- kondo config for linter
- changed calls to `tools.logging` to timbre
https://chat.flexiana.com/#narrow/stream/89-open-source/topic/xiana.2Ffrankie.20logging/near/431758

use timbre instead of `tools.logging`

---

.clj-kondo/config.edn
.github/workflows/clj-kondo.yml
.gitignore
examples/cli-chat/src/backend/cli_chat/controller_behaviors/chat.clj
examples/controllers/config/test/config.edn
examples/state-events/src/backend/state_events/interceptors/event_process.clj
src/framework/app/view/css/tailwind/core.cljc
src/framework/db/main.clj
src/framework/interceptor/core.clj
src/framework/scheduler/core.clj
src/framework/sse/core.clj
src/framework/webserver/core.clj
src/framework/websockets/core.clj
test/framework/web_socket/integration_test.clj

- added clj-kondo linter
- added config
- fixed linting issues in `src`
- [created a ticket](https://github.com/Flexiana/framework/projects/3#card-77499608) for `test` & `examples`

clj-kondo linter

---

examples/acl/project.clj
examples/cli-chat/src/backend/cli_chat/controllers/chat.clj
examples/cli-chat/src/backend/cli_chat/views/chat.clj
examples/state-events/project.clj
examples/state-events/test/integration/state_events/integration_test.clj
project.clj
src/framework/handler/core.clj
src/framework/route/core.clj
src/framework/sse/core.clj
src/framework/webserver/core.clj
test/framework/web_socket/integration_test.clj
test/framework/webserver/core_test.clj
test/framework_fixture.clj

Replace webserver

---

examples/acl/project.clj
examples/cli-chat/project.clj
examples/controllers/project.clj
examples/frames/project.clj
examples/sessions/project.clj
examples/state-events/project.clj
project.clj
src/framework/route/core.clj
src/framework/sse/core.clj

Fix sse issues

---

CHANGELOG.md
doc/tutorials.md
release.edn

Update version for 0.5.0-rc3 release
I'd like to make a release with the latest changes
A brief description of any steps needed to demonstrate the new functionality or show the bug is fixed

Update release 0.5.0 rc3

---

src/xiana/db.clj

Discussed at #239.
Can run tests.

Fixing the db-access

---

src/xiana/coercion.clj

#242 is declaring the problem. I track down the problem and find out that placing `:match` before the related interceptor is causing the problem. Placing them right in the interceptor seemed as the best solution. Or the according to the logic, `:match` would be partial and schemas can't be applied.
You can try to write a simple route with coercions.

Coercion Interceptor fix

---

CHANGELOG.md
src/xiana/db.clj

- needed to use non-psql database connections or custom datasources

Replace PgConnection pre-condition too java.sql.Connection

---

doc/getting-started.md

Fix typo in getting started doc

---

deps.edn
test/xiana/config_test.clj
test/xiana/interceptor/muuntaja_test.clj
test/xiana/interceptor/queue_test.clj
test/xiana/interceptor/wrap_test.clj
test/xiana/interceptor_test.clj
test/xiana/rbac/interceptor_test.clj
test/xiana/route/helpers_test.clj
test/xiana/route_test.clj
test/xiana/session_test.clj
test/xiana/state_test.clj
test/xiana/web_socket/integration_test.clj
test/xiana/web_socket/router_test.clj
test/xiana/webserver_test.clj

This PR will fix clj-kondo warnings and errors
Run:
```sh
clj -M:kondo
```
Check for warnings and errors.

Fix kondo warning and errors

---

CHANGELOG.md

Attempting a push to clojars....

Update to 0.5.0-rc4

---

src/xiana/swagger.clj
test/xiana/swagger_test.clj

- Fix swagger endpoint creation to just include `get` http verb
- Refactor code

Fix swagger endpoints and refactor code

---

deps.edn
examples/acl/test/comments_test.clj
examples/acl/test/helpers.clj
examples/acl/test/post_helpers.clj
examples/acl/test/posts_test.clj
examples/acl/test/users_test.clj
examples/jwt/test/integration_test.clj
examples/sessions/src/backend/app/controllers/login.clj
src/xiana/sse.clj
src/xiana/websockets.clj
test/xiana/web_socket/router_test.clj

Leave only one json library in deps (jsonista or data.json)

Leave only one json library in deps (jsonista or data.json)

---

src/xiana/db.clj
src/xiana/interceptor.clj
src/xiana/interceptor/queue.clj
src/xiana/rbac.clj

This PR fix some wrongs with logs in interceptor loop chain

Log cleanup

---

deps.edn

We need the latest `com.taoensso/timbre` to use new functionalities.  
All test should pass

Update timbre library

---

src/xiana/logging.clj

This will set the timbre level at config stage
All tests should pass

Set timbre log level in config
