- project.clj
- src/framework/acl/core.clj
- test/framework/acl/core_test.clj
The already implemented endpoints use the PUT http method for creating a resource and POST for updating it. This is against the convention that is followed by the industry. We need to use the POST http method for creating a resource and PUT for updating it.
> Exchange the POST and PUT http methods

- project.clj
- src/framework/components/web_server/core.clj
https://www.notion.so/flexiana/84c5d7907e8249a09ce5a60ff0f67b43?v=5fcfbc9a774c471d88ad46bf5ef11b9e&p=e6d75b780a1c4fe29981cfcacac5d822
**Why**
"We all hate that log" (c) Juan Ignacio Lopez
I deleted a `prn` func which prints all request data on every request. It made my developer experience very sad: my repl emacs buffer had tens of MBs of data after a short period of work and emacs was dying constantly when a request body was big (files). 
I have been using reifyhealth/lein-git-down plugin locally, which allows specifying specific commit as a dependency, to work around this issue, but I couldn't make it work with our CI (Github Actions). 
So it seems the easiest way is to merge this change into `main` and upload the new version to clojars.
> remove print in handler

- project.clj
- src/framework/cookies/core.clj
- src/framework/sse/core.clj
Updating framework version to v0.3.1
Fix for found bugs in SSE and cookies modules
- Cookies should be stored in browser, when it's injected to (-> state :response :cookies]).
- SSE channels must be closed on (user/stop-dev-system).
- SSE should open an async channel with (js/WebSocket. url) function.
> Fixing SSE and cookies bugs

- doc/intro.md
Fix some typos in `doc/intro.md`
> Fix typos in doc/intro.md

- doc/getting-started.md
The command 
```bash
docker exec -it todo-app-db-1 psql -U postgres -d todo_app
```
doesn't work to me with dash, instead it works with underscores
```bash
docker exec -it todo-app_db_1 psql -U postgres -d todo_app
```
Following the steps provided in the getting started page the command 
```bash
docker exec -it todo-app_db_1 psql -U postgres -d todo_app
```
doesn't work, throws the error 
```
Error: No such container: test-app-db-1
```
Now the error is not shown
> Update getting started

- examples/state-events/src/backend/state_events/controllers/event.clj
- examples/state-events/src/backend/state_events/interceptors/event_process.clj
- examples/state-events/src/backend/state_events/models/event.clj
- src/framework/db/core.clj
- src/framework/session/core.clj
Implement the protocols needed to handle conversion between Clj data (ie. HashMaps and Vectors) and jdbc PGobjects (containing JSON/JSONB).
This adds automatic support for DB queries which rely on `json_agg` and similar statements retrieving nested data.
> Marshalling between Clj data and db PGobjects

- examples/acl/project.clj
- examples/cli-chat/project.clj
- examples/cli-chat/src/backend/cli_chat/views/chat.clj
- examples/controllers/project.clj
- examples/frames/project.clj
- examples/sessions/project.clj
- examples/state-events/project.clj
- project.clj
- src/framework/sse/core.clj
- src/framework/websockets/core.clj
- test/framework/web_socket/integration_test.clj
All `jetty` related codes wrapped in the corresponding name space of Xiana
both `lein test` and `./example-test.sh` should be green
> hide server implementation

- config/test/config.edn
- examples/acl/project.clj
- examples/cli-chat/project.clj
- examples/controllers/project.clj
- examples/frames/project.clj
- examples/sessions/project.clj
- examples/state-events/project.clj
- project.clj
- src/framework/config/core.clj
- test/framework/config/core_test.clj
This PR makes possible to have configuration defined in a way like
```clojure
:email-address "$frankie-email | no-reply@frankie.com"
```
It's try to solve the `FRANKIE_EMAIL` key from already existing config keys 
- properties
- env
- config.edn
- file from :config key
- file from :framework-edn-config key
If it finds, then inject it, if doesn't it's use `no-reply@frankie.com` as default.
If no default provided and no variable set for the key, it sets it up as `nil`
new test provided for read value from env-variable
> Read config values from env keys

- CHANGELOG.md
- doc/interceptors.md
- src/xiana/interceptor.clj
- test/xiana/interceptor_test.clj
After discussion on Frankie's ticket [[2639]](https://www.notion.so/flexiana/2639-Ensure-malformed-GET-requests-are-rejected-8b309bd7005b4e83b961205813e967a9), the team decided to create an utility interceptor on Xiana that removed bodies from GET requests if included into the pipeline.
Run `lein test`. Test `prunes-get-request-bodies` must pass.
> [229] Creates interceptor to dissoc GET request bodies

- CHANGELOG.md
- config/dev/config.edn
- config/test/config.edn
- deps.edn
- doc/How-To.md
- src/xiana/db.clj
The support for custom datasource is needed for using some database connection pool, or for creating custom database access (in Frankie we need both). 
Maybe the name `:xiana/create-custom-datasource` is not the best, I can take other suggestions. 🤔 
- Check whether the everything is working as before
- Check whether using the `:xiana/create-custom-datasource` will create the right datasource with the defined jdbc options.
> Add support for custom datasource

- doc/getting-started.md
Fixed several problems in doc/getting-started.md:
1. node is also required to run frontend.
2. lein migrate create todos was failing with opaque message, turns out -n and -d arguments are required.
3. mapv in view function results in java.lang.IllegalArgumentException: No implementation of method: :write-body-to-stream of protocol: #'ring.core.protocols/StreamableResponseBody found for class: clojure.lang.PersistentVector . Change to map solves the problem.
4. Couple of indentation fixes.
> Getting started fix

- deps.edn
- src/xiana/interceptor.clj
- src/xiana/interceptor/cors.clj
- src/xiana/interceptor/error.clj
- src/xiana/interceptor/kebab_camel.clj
- src/xiana/jwt/interceptors.clj
- test/resources/multipart.csv
- test/xiana/interceptor/cors_test.clj
- test/xiana/interceptor/error_test.clj
- test/xiana/interceptor/kebab_camel_test.clj
- test/xiana/interceptor/multipart_test.clj
- test/xiana/interceptor/wrap_test.clj
- test/xiana/interceptor_test.clj
- test/xiana/jwt/interceptors_test.clj
- test/xiana/jwt_test.clj
- test/xiana/rbac/integration_test.clj
1. The allowed origin is configurable from env variables and in state it looks for `:cors-url` under `:deps` key
2. It also supports `preflight` requests
Error response
Error interceptor wrapped in `bad request` response instead of 200
1. Tiny but subtle improvement of params interceptor
2. Mock and Peridot library used for testing purposes as it allows us to simply mock multipart requests, and many others, but that's what we needed at the moment.
1. The first change I propose here is avoiding nesting coercion result under param type (path, query, form) and just keeping it under params
2. Validation error returns humanized details
If the back-end is Clojure and Front-end Javascript we encounter inconsistency of keys in the context of the language.
Hence the experimental solution that we …
> New interceptors and updates to existing ones

- .github/workflows/examples_test.yml
- .github/workflows/test.yml
- deps.edn
- examples/frames/project.clj
Dependencies for javax.servlet are dropped from ring.
We bumped ring version to 0.10.0 and added javax.servlet/servlet-api 2.5
Test your app as usual and see if it works. Ex. Frankie
> Bump ring version and add javax.servlet/servlet-api

- src/xiana/interceptor/kebab_camel.clj
- src/xiana/swagger.clj
- test/xiana/interceptor/kebab_camel_test.clj
The kebab-camel interceptor only transforms request from :params we need to work on all request types :body-params, :query-params, :path-params
> kebab camel interceptor for all request type

- deps.edn
This bumps hiccup to latest version
All test should pass!
> Bump hiccup/hiccup to version 2.0.0-RC2

- doc/How-To.md
- doc/tutorials.md
- docs/0.3.0/How-To.html
- examples/acl/src/backend/app/interceptors/load_user.clj
- examples/acl/src/backend/app/models/comments.clj
- examples/acl/src/backend/app/models/posts.clj
- examples/acl/src/backend/app/models/users.clj
- examples/sessions/src/backend/app/controllers/login.clj
- examples/sessions/src/backend/app/interceptors.clj
- examples/sessions/test/integration_test.clj
- examples/state-events/src/backend/state_events/interceptors/event_process.clj
- examples/state-events/test/integration/state_events/integration_test.clj
- examples/state-events/test/unit/state_events/event_process_test.clj
- src/xiana/coercion.clj
- src/xiana/interceptor.clj
- src/xiana/session.clj
- test/xiana/rbac/integration_test.clj
- test/xiana/rbac/interceptor_test.clj
- test/xiana/session_test.clj
- test/xiana/web_socket/integration_test.clj
This changes all java.util.UUID methods to clojure.core functions
All tests should pass
> Change all java.util.UUID to clojure.core uuid utilities

- src/xiana/swagger.clj
Just a little fn name change
All tests shall pass
> Fix a bad named function

- deps.edn
- src/xiana/hash.clj
- test/xiana/hash_test.clj
Include the fork of crypto-password which contains support for argon2 password hashing
> Add support of Argon2 key derivation function to xiana/hash

- src/xiana/logging.clj
Correct the logging function to be pure
A brief description of any steps needed to demonstrate the new functionality or show the bug is fixed
> Fix set-level to pure function

- src/xiana/db.clj
This commits make the db-queries at xiana.db to work if it is a function. Same functionality as query
> Make db-queries to work if function
